<?php
/******************************************************************************
* File: importexport.php
* Function: Hold text för all categories, head and sub
* Revision date: 2026-09-11
* Created by: Mikael Karlsson
* This file is distributed under the license:
* Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.
*
* This is a dummy file that does nothing but keep a list of names for the
* categries so that they can be picked up by this command:
* sudo find . -name "*.php" -print0"), sudo xargs -0 xgettext --join-existing
*
* This is quite a clever way to localize the categories
******************************************************************************/
// If this file is called by a browser, just exit
exit;

// Category_head
$dummy_array = array(
    _("Cable"),
    _("Capacitor"),
    _("Connector"),
    _("Diode"),
    _("IC"),
    _("Inductor"),
    _("Mechanic"),
    _("Optical"),
    _("Vaccum tubes"),
    _("Switch"),
    _("Power"),
    _("Resistor"),
    _("Transistor"),
    _("Display"),
    _("Sensor"),
    _("Module"),
    _("Miscellaneous"),
    _("Oscillator"),
// Category_sub
    _("Ribbon"),
    _("Coax"),
    _("Standard"),
    _("Mains"),
    _("Signal/Data"),
    _("Fiber optic"),
    _("Misc"),
    _("Ceramic"),
    _("Electrolytic"),
    _("Polyester"),
    _("Tantalum"),
    _("Variable"),
    _("Misc"),
    _("Audio"),
    _("Coax"),
    _("DC"),
    _("D-Sub"),
    _("HF"),
    _("PCB"),
    _("Mains"),
    _("Data"),
    _("Misc"),
    _("Rectifier"),
    _("Schottky"),
    _("Small Signal"),
    _("Zener"),
    _("Bridge"),
    _("Triac"),
    _("Diac"),
    _("Sidac"),
    _("Photo"),
    _("SCR"),
    _("Misc"),
    _("4xxx"),
    _("74xx"),
    _("74HC4xxx"),
    _("Comparator"),
    _("Op. Amp."),
    _("Temperature"),
    _("Timer & Osc."),
    _("Voltage Ref."),
    _("Voltage Reg."),
    _("A/D-D/A"),
    _("Switching"),
    _("Driver"),
    _("DataComm"),
    _("DC/DC Converter"),
    _("Audio/Video"),
    _("Memory"),
    _("Logic"),
    _("Microcontroller"),
    _("Microprocessor"),
    _("I2C"),
    _("1-wire"),
    _("Isolator"),
    _("Endode/Decode"),
    _("Converter"),
    _("EPROM"),
    _("RAM"),
    _("Counter/Timer"),
    _("PIO"),
    _("VIA"),
    _("PTM"),
    _("CTC"),
    _("ACIA"),
    _("PIA"),
    _("Real Time Clock"),
    _("Misc"),
    _("Ferrite"),
    _("Filter"),
    _("Inductor"),
    _("Transformer"),
    _("Misc"),
    _("Box"),
    _("Distance"),
    _("Fuse"),
    _("Motor"),
    _("Screw"),
    _("IC Socket"),
    _("Heat Sink"),
    _("Knob"),
    _("Meter"),
    _("Misc"),
    _("SSR[Relay]"),
    _("Laser"),
    _("LED"),
    _("LED 3mm"),
    _("LED 5mm"),
    _("Optocoupler"),
    _("IR LED"),
    _("7-segment LED"),
    _("Misc"),
    _("Octal"),
    _("Loctal B8G"),
    _("Heptal B7G"),
    _("Noval B9A"),
    _("Nixie"),
    _("Misc"),
    _("Keypad"),
    _("Momentary"),
    _("PCB Mounted"),
    _("Rotary Encoder"),
    _("Toggle Switch"),
    _("Relay"),
    _("DIP"),
    _("Misc"),
    _("Power Supply"),
    _("Transformer"),
    _("Wall Adapter"),
    _("Misc"),
    _("IGBT"),
    _("MOSFET N"),
    _("MOSFET P"),
    _("NPN"),
    _("PNP"),
    _("UJT"),
    _("PUT"),
    _("JFET N"),
    _("JFET P"),
    _("SIPMOS"),
    _("Misc"),
    _("0,25W Carbon 5%"),
    _("0,25W Metal 1%"),
    _("0,6W Metal 1%"),
    _("1W Carbon 5%"),
    _("0,1W SMD 0603"),
    _("0,125W SMD 0805"),
    _("0,25W SMD 1206"),
    _("Effect"),
    _("Photo"),
    _("Network"),
    _("Temperature"),
    _("Potentiometer"),
    _("Trimpots"),
    _("Trimpots multiturn"),
    _("Precision"),
    _("Misc"),
    _("LCD"),
    _("VFD"),
    _("TFT"),
    _("LED"),
    _("Nixie tubes"),
    _("Misc"),
    _("Moisture"),
    _("Temperature"),
    _("Pressure"),
    _("Magnetic"),
    _("Hall Effect"),
    _("Gas"),
    _("Accelerometer"),
    _("Light"),
    _("Proximity"),
    _("Misc"),
    _("GSM"),
    _("GPS"),
    _("Bluetooth"),
    _("WiFi"),
    _("ZigBee"),
    _("RFID"),
    _("Arduino"),
    _("MSP430"),
    _("chipKIT"),
    _("Raspberry Pi"),
    _("BeagleBone"),
    _("Misc"),
    _("Misc"),
    _("Crystal"),
    _("Resonator"),
    _("TCXO"),
    _("Clock Module"),
    _("Misc"));
?>